### ISSUE TITLE
Issue Creating a tale

### ISSUE THREAD

**Issue by ian-taylor** [whole-tale/girder_ythub#9]
I am posting:

curl 'https://girder.wholetale.org/api/v1/tale/?imageId=58caa5ac9fcbde0001df4d24folderId=58c2c6a7b270e80001b45544name=Ians%20FE&description=Testingpublic=trueconfig=%7B%7D' -X POST -H 'Origin: http://localhost:4200' -H 'Accept-Encoding: gzip, deflate, br' -H 'Accept-Language: en-US,en;q=0.8,nl;q=0.6' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36' -H 'Accept: */*' -H 'Referer: http://localhost:4200/compose' -H 'Connection: keep-alive' -H 'Girder-Token: XXX' -H 'Content-Length: 0' —compressed

where XXX is your girderToken

And getting this error:

{"message": "You need to specify either an \"instanceId\" or an \"imageId\" and a \"folderId\".", "type": "rest”}

When there is an image and folder id supplied.

**Comment by Xarthisius** [comment]
URL is malformed AFAICT. You're missing `&` between params. What you got there is just `imageId` with a lot of junk.

**Comment by ian-taylor** [comment]
Client error.
